OUTPUT_DIR: str = "./models"
PLANTUML_MODEL_NAME: str = "umlement.puml"
RESOURCES_DIR: str = "./resources"
SUPPORTED_OUTPUT_FORMATS: tuple[str, ...] = ("png", "svg")
PLANTUML_HEADER_LINES: tuple[str, ...] = (
    "skinparam backgroundColor #F8FAFC",
    "skinparam shadowing false",
    "skinparam dpi 200",
    "skinparam defaultFontName Inter",
    "skinparam defaultFontSize 13",
    "skinparam linetype polyline",
    "left to right direction",
    "skinparam ArrowColor #64748B",
    "skinparam ArrowThickness 1.3",
    "skinparam ArrowFontColor #475569",
    "skinparam ArrowFontSize 10",
    "skinparam RoundCorner 12",
    "skinparam Padding 8",
    "skinparam ClassFontStyle bold",
    "skinparam PackageStyle rectangle",
    "skinparam package {",
    "  BackgroundColor #EEF2FF",
    "  BorderColor #CBD5E1",
    "  FontColor #0F172A",
    "  FontStyle bold",
    "  RoundCorner 14",
    "}",
    "skinparam class {",
    "  BackgroundColor #FFFFFF",
    "  BorderColor #334155",
    "  FontColor #0F172A",
    "  AttributeFontColor #475569",
    "  AttributeFontSize 11",
    "  StereotypeFontColor #6366F1",
    "  HeaderBackgroundColor #E0E7FF",
    "}",
    "skinparam note {",
    "  BackgroundColor #FFF7ED",
    "  BorderColor #FDBA74",
    "  FontColor #7C2D12",
    "  RoundCorner 10",
    "}",
)
