from __future__ import annotations

from typing import Protocol


class ProgressSink(Protocol):
    def start(self, label: str, detail: str | None = None) -> None: ...
    def advance(self, label: str, detail: str | None = None) -> None: ...
    def complete(self, label: str, detail: str | None = None) -> None: ...
    def info(self, label: str, detail: str | None = None) -> None: ...
