name: CI/CD
run-name: CI/CD pipeline initiated

on:
  push:
    branches:
      - SIT
      - PROD
  pull_request:
    branches:
      - PROD

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: pip

      - name: Run linter
        shell: bash
        # NOTE remove `--exit-zero` to force the pipeline build to fail if linter discrepancies are found
        run: |
          pip install pylint --quiet
          pylint $(git ls-files "*.py") --exit-zero

  mypy:
    runs-on: ubuntu-latest
    needs: pylint
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: pip

      - name: Run static type checks
        shell: bash
        run: |
          pip install mypy --quiet
          pip install -r requirements.txt --quiet
          mypy $(git ls-files "*.py")

  pytest:
    runs-on: ubuntu-latest
    needs: mypy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: pip

      - name: Run unit tests
        shell: bash
        run: |
          pip install pytest --quiet
          pytest tests/ --quiet

  pytest-cov:
    runs-on: ubuntu-latest
    needs: pytest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: pip

      - name: Generate code coverage report
        shell: bash
        run: |
          pip install pytest-cov coveralls --quiet
          pytest --cov tests/ --cov-report html:coverage/coverage_report/ --cov-config coverage/.coveragerc

      - name: Upload code coverage report to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload code coverage report artifact
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage/coverage_report/
          if-no-files-found: error
          retention-days: 0

  pdoc3:
    runs-on: ubuntu-latest
    needs: pytest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: pip

      - name: Generate code documentation
        shell: bash
        run: |
          pip install pdoc3 --quiet
          pip install -r requirements.txt --quiet
          pdoc --force --html $(git ls-files "*.py") --output-dir docs/

      - name: Upload code documentation artifact
        uses: actions/upload-artifact@v3
        with:
          name: code-documentation
          path: docs/
          if-no-files-found: error
          retention-days: 0
